sudo: required
language: ruby
rvm:
- 2.4.2
services:
- docker
script:
- "./build_images.sh"
notifications:
  slack:
    rooms:
      secure: VCVk/Trzs0jz/XquFBeF9IkgvplhUUR2lNqodamULvWiGR6uSsGMJ0Breseh23YMOCWrXW9tb0WGxYJC07+Umff5LH1mrW1NlQ96UEO/z0DDFwtSzmkttcEQ6K59ggpFtewSvanjt080bqvJXOEM7DZAc/IIuXlXGgqEnCQ3VURLfeh4U4EVsINcwlSdhMGHywkknyfiADp+qSUwvVaa04wN8JJt6vbxvw3dKmkDNg1pSPQwpJXRc/iiSzECK7AQT3I49ghhKMmn/s1ooke+I1iRISYkmV20T9Usbni6xsmNJAyOIxXXnWxunurVPAktfUfvDkCysEdaO/tGsQpr5nRz2XC87wMfXb5ezDIpU6QPYnrAYZeeXJyQ0WY1ld4KvlOa/pQEBW+K/mmlLN0W0ZnhukzjinZpuxE4021j6JHNrx4b6PmKSvPyS7/LtunvfKZBI4KR7Jp4imp6vybzwVW4ffBIUmKMq1HZ4KTt59Rrx2C6F0hUHNPlDjhNRtafOh026Qcf07Cs4w662jGgnUwLBfygYGkna29eplBpWx7/EYpR7P9BzWPHLFYG+9OxXsIKeskcuNunJRQH/vQ2Aly1tP7s3/App8ZdeLBEw3/qO7deb68W2T1tF5Y2sBV7HZu6tNASJExUhnB44D/SdgH7sIPokabbNvTskl+ZGfM=
