development:
  cassandra:
    hosts: [localhost]
    port: 9042
    username: ''
    password: ''
    keyspace: xadf

  mongo:
    url: 'mongodb://127.0.0.1:27017/xadf'
  
  git_branch: 'master'
  allowed_formats: [package, rule, table]

production:
  cassandra:
    hosts: [localhost]
    port: 9042
    username: ''
    password: ''
    keyspace: xadf

  mongo:
    url: 'mongodb://mongodb.marathon.l4lb.thisdcos.directory:27017/xadf'
  
  git_branch: 'master'
  allowed_formats: [package, rule, table]
