development:
  db_hosts: [localhost]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf

  git_branch: 'master'
  allowed_formats: [package, rule, table]

production:
  db_hosts: [localhost]
  db_port: 9042
  db_username: ''
  db_password: ''
  db_keyspace: xadf

  git_branch: 'master'
  allowed_formats: [package, rule, table]